name: Auto Deploy Contributor Branch

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

    - name: Install Railway CLI
      run: curl -fsSL https://railway.app/install.sh | sh

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Deploy branch to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        echo "Deploying branch: $BRANCH"

        # Init project (project name = branch name)
        railway init --name "$BRANCH" --yes
        # Deploy
        railway up

    - name: Get Public URL
      id: get_url
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        PROJECT_ID=$(./railway project list --json | jq -r ".projects[] | select(.name==\"$BRANCH\") | .id")
        PUBLIC_URL=$(./railway domain list --project $PROJECT_ID --json | jq -r ".[0].url")

        echo "✅ Your app is deployed at: https://$PUBLIC_URL"
        echo "public_url=https://$PUBLIC_URL" >> $GITHUB_OUTPUT

    - name: Post URL to Summary
      run: |
        echo "### ✅ Your app is deployed at: ${{ steps.get_url.outputs.public_url }}" >> $GITHUB_STEP_SUMMARY
    
    - name: Comment to PR
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          🚀 **Preview URL:** [${{ steps.get_url.outputs.public_url }}](https://${{ steps.get_url.outputs.public_url }})
